# Generated by Django 6.0.5 on 2026-05-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20, unique=True)),
                ('emp_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('experience', models.IntegerField()),
                ('primary_skill', models.CharField(max_length=100)),
                ('secondary_skill', models.CharField(max_length=100)),
                ('cm_name', models.CharField(max_length=100)),
                ('profile_status', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('date_shared', models.DateField()),
                ('project_owner', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
